# Generated by Django 2.2.17 on 2020-12-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtransaction',
            old_name='dropoff',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='bookingtransaction',
            name='pickup',
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='distance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='timestamp_arrive',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='timestamp_depart',
            field=models.DateTimeField(blank=True),
        ),
    ]
